```
const log = i => {
    console.log(i, 'start');
    if (i + 1 < 10) {
        log(i + 1)
    }
    console.log(i,'end')
}
log(0)

0 "start"
1 "start"
2 "start"
3 "start"
4 "start"
5 "start"
6 "start"
7 "start"
8 "start"
9 "start"
9 "end"
8 "end"
7 "end"
6 "end"
5 "end"
4 "end"
3 "end"
2 "end"
1 "end"
0 "end"
```

![递归断点演示](https://github.com/Zwn09266951/Learning-Team/blob/master/zwn/JavaScript/递归/digui.gif "递归断点演示")

通过以上断点可以看出   
log函数调用自身的時候，由于调用栈的原因沒有进入到第二个log，直接进入了log函数  
所以出现了 先进后出的现象
